color_gray_100 = "#1e1e1e"
color_gray_200 = "#353535"
color_gray_300 = "#4b4b4b"
color_gray_400 = "#626262"
color_gray_500 = "#787878"
color_gray_600 = "#8f8f8f"
color_gray_700 = "#a5a5a5"
color_gray_800 = "#bcbcbc"
color_gray_900 = "#d2d2d2"
color_gray_1000 = "#e9e9e9"
color_white = "#ffffff"

color_accent_100 = "#001829"
color_accent_200 = "#003152"
color_accent_300 = "#00497a"
color_accent_400 = "#0062a3"
color_accent_500 = "#007acc"
color_accent = "#007acc"
color_accent_600 = "#3395d6"
color_accent_700 = "#66afe0"
color_accent_800 = "#99caeb"
color_accent_900 = "#cce4f5"

