username = "flo"

color_gray_100 = "#1e1e1e"
color_gray_200 = "#353535"
color_gray_300 = "#4b4b4b"
color_gray_400 = "#626262"
color_gray_500 = "#787878"
color_gray_600 = "#8f8f8f"
color_gray_700 = "#a5a5a5"
color_gray_800 = "#bcbcbc"
color_gray_900 = "#d2d2d2"
color_gray_1000 = "#e9e9e9"
color_white = "#ffffff"

color_accent_100 = "#001829"
color_accent_200 = "#003152"
color_accent_300 = "#00497a"
color_accent_400 = "#0062a3"
color_accent_500 = "#007acc"
color_accent = "#007acc"
color_accent_600 = "#3395d6"
color_accent_700 = "#66afe0"
color_accent_800 = "#99caeb"
color_accent_900 = "#cce4f5"

nord_blackest = "#000000"
nord_blacker = "#1D222D"
nord_black = "#2E3440"
nord_dark_gray = "#3B4252"
nord_gray = "#434C5E"
nord_light_gray = "#4C566A"
nord_light_gray_bright = "#616E88"
nord_darkest_white = "#D8DEE9"
nord_darker_white = "#E5E9F0"
nord_white = "#ECEFF4"
nord_teal = "#8FBCBB"
nord_off_blue = "#88C0D0"
nord_glacier = "#81A1C1"
nord_blue = "#5E81AC"
nord_red = "#BF616A"
nord_orange = "#D08770"
nord_yellow = "#EBCB8B"
nord_green = "#A3BE8C"
nord_purple = "#B48EAD"