"$schema" = 'https://starship.rs/config-schema.json'

format = """
${custom.user_local}${custom.user_ssh}\
${custom.arrow_local}${custom.arrow_ssh}\
$directory\
[](fg:base03 bg:base04)\
$git_branch\
$git_commit\
$git_status\
[](fg:base04)\
\n$character"""

[custom.user_local]
when = 'test -z "$SSH_CONNECTION"'
command = 'printf "%s" "$USER"'
shell = ["sh", "--noprofile", "--norc"]
format = '[ $output ](fg:base00 bg:blue)'

[custom.user_ssh]
when = 'test -n "$SSH_CONNECTION"'
command = 'printf "ssh %s@%s" "$USER" "${HOSTNAME:-$HOST}"'
shell = ["sh", "--noprofile", "--norc"]
format = '[ $output ](fg:base07 bg:red)'

[custom.arrow_local]
when = 'test -z "$SSH_CONNECTION"'
command = 'true'
shell = ["sh", "--noprofile", "--norc"]
format = '[](bg:base03 fg:blue)'

[custom.arrow_ssh]
when = 'test -n "$SSH_CONNECTION"'
command = 'true'
shell = ["sh", "--noprofile", "--norc"]
format = '[](bg:base03 fg:red)'

[directory]
style = "fg:base07 bg:base03"
format = "[ $path ]($style)"

[git_branch]
symbol = "git"
style = "bg:base04"
format = '[[ $symbol $branch ](fg:base00 bg:base04)]($style)'

[git_commit]
tag_symbol = " tag "
style = "bg:base04"
format = '[[$hash$tag ](fg:base00 bg:base04)]($style)'

[git_status]
style = "bg:base04"
format = '[[($all_status$ahead_behind )](fg:base00 bg:base04)]($style)'
ahead = "+"
behind = "-"
diverged = "+-"
renamed = "r"
deleted = "x"
